### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by AlexHedley**
Added 'Open Android Manifest' for macOS

Started work on XAML IntelliSense, needs more work.

A few typos corrected

Added Tabs
- [mkdocs-material 955](https://github.com/squidfunk/mkdocs-material/issues/955)
```
  - pymdownx.tabbed
  - pymdownx.superfences
```

### CODE REVIEW

**Comment by matthewrdev** [comment]
Thanks for the contribution @AlexHedley.

I can see that there are additional mkdocs extensions included in your pull request. Do these extensions require additional installation and, if so, can you add instructions to the contribution guide on installing these extensions locally?

**Comment by AlexHedley** [comment]
@matthewrdev do we not already have [PyMdown Extensions](https://facelessuser.github.io/pymdown-extensions/)?
[Material for MkDocs](https://squidfunk.github.io/mkdocs-material/extensions/pymdown/) mentions 
> A compatible version is always included with the theme.

Sorry if this isn't the case, I wouldn't have introduced a new dependency otherwise.

**Comment by matthewrdev** [comment]
@AlexHedley The tab extension elegantly solves a problem I'd been on/off trying to figure out for a while so the addition is appreciated. The new docs look good, keep it coming!

**Comment by AlexHedley** [comment]
Thought it was best to get reviewed now as not sure when I'll next be able to look at it, so get's the current changes added.

**Comment by ravero** [comment]
Hi @AlexHedley, is it ready for merge? Please confirm me so I'll proceed with the review.

**Pull request merged**
